### ISSUE TITLE
TAMBAHAN DARI GUA

### ISSUE THREAD

**Issue by fhryazr** [fhryazr/projek-uts-grafkom-cermin-cekung#2]
@Rothiii Hal yg perlu di baikin:
- DDA (khususnya yang diagonal)
- eror handling jika input bukan int
- Tambahkan fitur slider

**Comment by Rothiii** [comment]
tambahan lainnya :
1. membuat objek selain garis lurus
2. (opsional) buat fitur non aktif dan aktif garis 
3. (opsioanl) buat slider
